[tool.poetry]
name = "experimentus"
version = "0.1.0"
description = ""
authors = ["ekaterina besshtannikova <dolmatova3010@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
